name: Main

on: workflow_dispatch

jobs:
  Build:
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Windows
            os: windows-2025
            buildArgs: windows
            setupCommand: .\"setup/windows.bat"
            artifactName: windowsBuild-x86_64
            artifactPath: export/release/windows/bin/*
            ref: main
          - name: Linux
            os: ubuntu-22.04
            buildArgs: linux
            setupCommand: sh ./setup/unix.sh
            artifactName: linuxBuild-x86_64
            artifactPath: export/release/linux/bin/*
            ref: main
          - name: macOS x86_64
            os: macos-15
            setupCommand: sh ./setup/unix.sh
            buildArgs: "mac -64 -D HXCPP_M64"
            artifactName: macOSBuild-x86_64
            artifactPath: export/release/macos/bin/*
            ref: main
          - name: macOS ARM64
            os: macos-15
            setupCommand: sh ./setup/unix.sh
            buildArgs: "mac -arm64 -D HXCPP_ARM64"
            artifactName: macOSBuild-arm64
            artifactPath: export/release/macos/bin/*
            ref: main
          - name: Android
            os: macos-15
            buildArgs: "android -ONLY_ARM64"
            setupCommand: sh ./setup/unix.sh
            artifactName: androidBuild
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
            ref: mobile
          - name: iOS
            os: macos-15
            buildArgs: "ios -nosign"
            setupCommand: sh ./setup/unix.sh
            artifactName: iOSBuild
            artifactPath: "export/release/ios/build/Release-iphoneos/*.ipa"
            ref: mobile
    uses: ./.github/workflows/build.yml
    secrets:
      TH2L_ENGINE_NAME: ${{ secrets.TH2L_ENGINE_NAME }}
      TH2L_MODPACK_NAME: ${{ secrets.TH2L_MODPACK_NAME }}
      TH2L_ORGANIZATION_TOKEN: ${{ secrets.TH2L_ORGANIZATION_TOKEN }}
      TH2L_ARTIFACT_PASSWORD: ${{ secrets.TH2L_ARTIFACT_PASSWORD }}
    with:
        name: ${{ matrix.name }}
        os: ${{ matrix.os }}
        buildArgs: ${{ matrix.buildArgs }}
        setupCommand: ${{ matrix.setupCommand }}
        artifactName: ${{ matrix.artifactName }}
        artifactPath: ${{ matrix.artifactPath }}
        ref: ${{ matrix.ref }}
